// This file is @generated by prost-build.
/// Request để yêu cầu thông tin validators của một block
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockRequest {
    #[prost(uint64, tag = "1")]
    pub block_number: u64,
}
/// StringStringPair định nghĩa một cặp key-value dạng chuỗi
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StringStringPair {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// Danh sách các validators
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidatorList {
    #[prost(message, repeated, tag = "1")]
    pub validators: ::prost::alloc::vec::Vec<Validator>,
}
/// Thông tin chi tiết của một validator
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Validator {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub website: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub is_jailed: bool,
    #[prost(message, optional, tag = "6")]
    pub jailed_until: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int64, tag = "7")]
    pub missed_blocks_counter: i64,
    #[prost(uint64, tag = "8")]
    pub commission_rate: u64,
    #[prost(string, tag = "9")]
    pub min_self_delegation: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub delegators: ::prost::alloc::vec::Vec<StringStringPair>,
    #[prost(string, tag = "11")]
    pub accumulated_rewards_per_share: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "12")]
    pub delegator_reward_indexes: ::prost::alloc::vec::Vec<StringStringPair>,
    #[prost(string, tag = "13")]
    pub image: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub primary_address: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub total_staked_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "16")]
    pub worker_address: ::prost::alloc::string::String,
    #[prost(string, tag = "17")]
    pub p2p_address: ::prost::alloc::string::String,
    #[prost(string, tag = "18")]
    pub pubkey_bls: ::prost::alloc::string::String,
    #[prost(string, tag = "19")]
    pub pubkey_secp: ::prost::alloc::string::String,
}
/// Thêm một loại request/response mới để làm ví dụ
///
/// Không cần tham số gì, chỉ cần hỏi status
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStatus {
    #[prost(string, tag = "1")]
    pub status_message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub uptime_seconds: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    /// oneof đảm bảo chỉ một trong các trường sau có thể được set tại một thời điểm
    #[prost(oneof = "request::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<request::Payload>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    /// oneof đảm bảo chỉ một trong các trường sau có thể được set tại một thời điểm
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        BlockRequest(super::BlockRequest),
        /// Thêm các loại request khác ở đây trong tương lai
        #[prost(message, tag = "2")]
        StatusRequest(super::StatusRequest),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(oneof = "response::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<response::Payload>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        ValidatorList(super::ValidatorList),
        /// Thêm các loại response khác ở đây
        #[prost(message, tag = "2")]
        ServerStatus(super::ServerStatus),
    }
}
