// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: bls_account.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlsAccountData lưu thông tin account đã đăng ký BLS
type BlsAccountData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                                       // 20 bytes (Ethereum address)
	BlsPublicKey   []byte                 `protobuf:"bytes,2,opt,name=bls_public_key,json=blsPublicKey,proto3" json:"bls_public_key,omitempty"`       // BLS public key bytes
	RegisteredAt   int64                  `protobuf:"varint,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`        // Unix timestamp
	RegisterTxHash []byte                 `protobuf:"bytes,4,opt,name=register_tx_hash,json=registerTxHash,proto3" json:"register_tx_hash,omitempty"` // 32 bytes (transaction hash)
	IsConfirmed    bool                   `protobuf:"varint,5,opt,name=is_confirmed,json=isConfirmed,proto3" json:"is_confirmed,omitempty"`
	ConfirmedAt    int64                  `protobuf:"varint,6,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	ConfirmTxHash  []byte                 `protobuf:"bytes,7,opt,name=confirm_tx_hash,json=confirmTxHash,proto3" json:"confirm_tx_hash,omitempty"` // 32 bytes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlsAccountData) Reset() {
	*x = BlsAccountData{}
	mi := &file_bls_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlsAccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlsAccountData) ProtoMessage() {}

func (x *BlsAccountData) ProtoReflect() protoreflect.Message {
	mi := &file_bls_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlsAccountData.ProtoReflect.Descriptor instead.
func (*BlsAccountData) Descriptor() ([]byte, []int) {
	return file_bls_account_proto_rawDescGZIP(), []int{0}
}

func (x *BlsAccountData) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BlsAccountData) GetBlsPublicKey() []byte {
	if x != nil {
		return x.BlsPublicKey
	}
	return nil
}

func (x *BlsAccountData) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *BlsAccountData) GetRegisterTxHash() []byte {
	if x != nil {
		return x.RegisterTxHash
	}
	return nil
}

func (x *BlsAccountData) GetIsConfirmed() bool {
	if x != nil {
		return x.IsConfirmed
	}
	return false
}

func (x *BlsAccountData) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *BlsAccountData) GetConfirmTxHash() []byte {
	if x != nil {
		return x.ConfirmTxHash
	}
	return nil
}

// PendingTransaction lưu giao dịch chưa confirm
type PendingTransaction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Address           []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BlsPublicKey      []byte                 `protobuf:"bytes,2,opt,name=bls_public_key,json=blsPublicKey,proto3" json:"bls_public_key,omitempty"`
	RawTransactionHex string                 `protobuf:"bytes,3,opt,name=raw_transaction_hex,json=rawTransactionHex,proto3" json:"raw_transaction_hex,omitempty"` // Changed: Lưu hex string thay vì bytes
	CreatedAt         int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Nonce             uint64                 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	OriginalGasPrice  uint64                 `protobuf:"varint,6,opt,name=original_gas_price,json=originalGasPrice,proto3" json:"original_gas_price,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PendingTransaction) Reset() {
	*x = PendingTransaction{}
	mi := &file_bls_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTransaction) ProtoMessage() {}

func (x *PendingTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bls_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTransaction.ProtoReflect.Descriptor instead.
func (*PendingTransaction) Descriptor() ([]byte, []int) {
	return file_bls_account_proto_rawDescGZIP(), []int{1}
}

func (x *PendingTransaction) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PendingTransaction) GetBlsPublicKey() []byte {
	if x != nil {
		return x.BlsPublicKey
	}
	return nil
}

func (x *PendingTransaction) GetRawTransactionHex() string {
	if x != nil {
		return x.RawTransactionHex
	}
	return ""
}

func (x *PendingTransaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PendingTransaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *PendingTransaction) GetOriginalGasPrice() uint64 {
	if x != nil {
		return x.OriginalGasPrice
	}
	return 0
}

// NEW: Tách danh sách confirmed và unconfirmed
type BlsAccountList struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Accounts      []*BlsAccountList_AccountEntry `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlsAccountList) Reset() {
	*x = BlsAccountList{}
	mi := &file_bls_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlsAccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlsAccountList) ProtoMessage() {}

func (x *BlsAccountList) ProtoReflect() protoreflect.Message {
	mi := &file_bls_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlsAccountList.ProtoReflect.Descriptor instead.
func (*BlsAccountList) Descriptor() ([]byte, []int) {
	return file_bls_account_proto_rawDescGZIP(), []int{2}
}

func (x *BlsAccountList) GetAccounts() []*BlsAccountList_AccountEntry {
	if x != nil {
		return x.Accounts
	}
	return nil
}

// NEW: Batch transaction data
type BatchBlsAccountData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*BlsAccountData      `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchBlsAccountData) Reset() {
	*x = BatchBlsAccountData{}
	mi := &file_bls_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchBlsAccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBlsAccountData) ProtoMessage() {}

func (x *BatchBlsAccountData) ProtoReflect() protoreflect.Message {
	mi := &file_bls_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBlsAccountData.ProtoReflect.Descriptor instead.
func (*BatchBlsAccountData) Descriptor() ([]byte, []int) {
	return file_bls_account_proto_rawDescGZIP(), []int{3}
}

func (x *BatchBlsAccountData) GetAccounts() []*BlsAccountData {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type BatchPendingTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*PendingTransaction  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPendingTransaction) Reset() {
	*x = BatchPendingTransaction{}
	mi := &file_bls_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPendingTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPendingTransaction) ProtoMessage() {}

func (x *BatchPendingTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bls_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPendingTransaction.ProtoReflect.Descriptor instead.
func (*BatchPendingTransaction) Descriptor() ([]byte, []int) {
	return file_bls_account_proto_rawDescGZIP(), []int{4}
}

func (x *BatchPendingTransaction) GetTransactions() []*PendingTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type BlsAccountList_AccountEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	IsConfirmed   bool                   `protobuf:"varint,2,opt,name=is_confirmed,json=isConfirmed,proto3" json:"is_confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlsAccountList_AccountEntry) Reset() {
	*x = BlsAccountList_AccountEntry{}
	mi := &file_bls_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlsAccountList_AccountEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlsAccountList_AccountEntry) ProtoMessage() {}

func (x *BlsAccountList_AccountEntry) ProtoReflect() protoreflect.Message {
	mi := &file_bls_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlsAccountList_AccountEntry.ProtoReflect.Descriptor instead.
func (*BlsAccountList_AccountEntry) Descriptor() ([]byte, []int) {
	return file_bls_account_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BlsAccountList_AccountEntry) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BlsAccountList_AccountEntry) GetIsConfirmed() bool {
	if x != nil {
		return x.IsConfirmed
	}
	return false
}

var File_bls_account_proto protoreflect.FileDescriptor

const file_bls_account_proto_rawDesc = "" +
	"\n" +
	"\x11bls_account.proto\x12\x05proto\"\x8d\x02\n" +
	"\x0eBlsAccountData\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12$\n" +
	"\x0ebls_public_key\x18\x02 \x01(\fR\fblsPublicKey\x12#\n" +
	"\rregistered_at\x18\x03 \x01(\x03R\fregisteredAt\x12(\n" +
	"\x10register_tx_hash\x18\x04 \x01(\fR\x0eregisterTxHash\x12!\n" +
	"\fis_confirmed\x18\x05 \x01(\bR\visConfirmed\x12!\n" +
	"\fconfirmed_at\x18\x06 \x01(\x03R\vconfirmedAt\x12&\n" +
	"\x0fconfirm_tx_hash\x18\a \x01(\fR\rconfirmTxHash\"\xe7\x01\n" +
	"\x12PendingTransaction\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12$\n" +
	"\x0ebls_public_key\x18\x02 \x01(\fR\fblsPublicKey\x12.\n" +
	"\x13raw_transaction_hex\x18\x03 \x01(\tR\x11rawTransactionHex\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12,\n" +
	"\x12original_gas_price\x18\x06 \x01(\x04R\x10originalGasPrice\"\x9d\x01\n" +
	"\x0eBlsAccountList\x12>\n" +
	"\baccounts\x18\x01 \x03(\v2\".proto.BlsAccountList.AccountEntryR\baccounts\x1aK\n" +
	"\fAccountEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12!\n" +
	"\fis_confirmed\x18\x02 \x01(\bR\visConfirmed\"H\n" +
	"\x13BatchBlsAccountData\x121\n" +
	"\baccounts\x18\x01 \x03(\v2\x15.proto.BlsAccountDataR\baccounts\"X\n" +
	"\x17BatchPendingTransaction\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.proto.PendingTransactionR\ftransactionsB5Z3github.com/meta-node-blockchain/meta-node/pkg/protob\x06proto3"

var (
	file_bls_account_proto_rawDescOnce sync.Once
	file_bls_account_proto_rawDescData []byte
)

func file_bls_account_proto_rawDescGZIP() []byte {
	file_bls_account_proto_rawDescOnce.Do(func() {
		file_bls_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bls_account_proto_rawDesc), len(file_bls_account_proto_rawDesc)))
	})
	return file_bls_account_proto_rawDescData
}

var file_bls_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bls_account_proto_goTypes = []any{
	(*BlsAccountData)(nil),              // 0: proto.BlsAccountData
	(*PendingTransaction)(nil),          // 1: proto.PendingTransaction
	(*BlsAccountList)(nil),              // 2: proto.BlsAccountList
	(*BatchBlsAccountData)(nil),         // 3: proto.BatchBlsAccountData
	(*BatchPendingTransaction)(nil),     // 4: proto.BatchPendingTransaction
	(*BlsAccountList_AccountEntry)(nil), // 5: proto.BlsAccountList.AccountEntry
}
var file_bls_account_proto_depIdxs = []int32{
	5, // 0: proto.BlsAccountList.accounts:type_name -> proto.BlsAccountList.AccountEntry
	0, // 1: proto.BatchBlsAccountData.accounts:type_name -> proto.BlsAccountData
	1, // 2: proto.BatchPendingTransaction.transactions:type_name -> proto.PendingTransaction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bls_account_proto_init() }
func file_bls_account_proto_init() {
	if File_bls_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bls_account_proto_rawDesc), len(file_bls_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bls_account_proto_goTypes,
		DependencyIndexes: file_bls_account_proto_depIdxs,
		MessageInfos:      file_bls_account_proto_msgTypes,
	}.Build()
	File_bls_account_proto = out.File
	file_bls_account_proto_goTypes = nil
	file_bls_account_proto_depIdxs = nil
}
