// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: contract_free_gas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractFreeGasData lưu thông tin contract được miễn phí gas (chỉ lưu address)
type ContractFreeGasData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress []byte                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // 20 bytes (Ethereum address)
	AddedAt         int64                  `protobuf:"varint,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`                        // Unix timestamp khi thêm vào
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContractFreeGasData) Reset() {
	*x = ContractFreeGasData{}
	mi := &file_contract_free_gas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractFreeGasData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractFreeGasData) ProtoMessage() {}

func (x *ContractFreeGasData) ProtoReflect() protoreflect.Message {
	mi := &file_contract_free_gas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractFreeGasData.ProtoReflect.Descriptor instead.
func (*ContractFreeGasData) Descriptor() ([]byte, []int) {
	return file_contract_free_gas_proto_rawDescGZIP(), []int{0}
}

func (x *ContractFreeGasData) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *ContractFreeGasData) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

// ContractFreeGasList dùng cho pagination response
type ContractFreeGasList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contracts     []*ContractFreeGasData `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractFreeGasList) Reset() {
	*x = ContractFreeGasList{}
	mi := &file_contract_free_gas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractFreeGasList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractFreeGasList) ProtoMessage() {}

func (x *ContractFreeGasList) ProtoReflect() protoreflect.Message {
	mi := &file_contract_free_gas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractFreeGasList.ProtoReflect.Descriptor instead.
func (*ContractFreeGasList) Descriptor() ([]byte, []int) {
	return file_contract_free_gas_proto_rawDescGZIP(), []int{1}
}

func (x *ContractFreeGasList) GetContracts() []*ContractFreeGasData {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *ContractFreeGasList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ContractFreeGasList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ContractFreeGasList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ContractFreeGasList) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_contract_free_gas_proto protoreflect.FileDescriptor

const file_contract_free_gas_proto_rawDesc = "" +
	"\n" +
	"\x17contract_free_gas.proto\x12\x05proto\"[\n" +
	"\x13ContractFreeGasData\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\fR\x0fcontractAddress\x12\x19\n" +
	"\badded_at\x18\x02 \x01(\x03R\aaddedAt\"\xb7\x01\n" +
	"\x13ContractFreeGasList\x128\n" +
	"\tcontracts\x18\x01 \x03(\v2\x1a.proto.ContractFreeGasDataR\tcontracts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPagesB5Z3github.com/meta-node-blockchain/meta-node/pkg/protob\x06proto3"

var (
	file_contract_free_gas_proto_rawDescOnce sync.Once
	file_contract_free_gas_proto_rawDescData []byte
)

func file_contract_free_gas_proto_rawDescGZIP() []byte {
	file_contract_free_gas_proto_rawDescOnce.Do(func() {
		file_contract_free_gas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_free_gas_proto_rawDesc), len(file_contract_free_gas_proto_rawDesc)))
	})
	return file_contract_free_gas_proto_rawDescData
}

var file_contract_free_gas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_free_gas_proto_goTypes = []any{
	(*ContractFreeGasData)(nil), // 0: proto.ContractFreeGasData
	(*ContractFreeGasList)(nil), // 1: proto.ContractFreeGasList
}
var file_contract_free_gas_proto_depIdxs = []int32{
	0, // 0: proto.ContractFreeGasList.contracts:type_name -> proto.ContractFreeGasData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contract_free_gas_proto_init() }
func file_contract_free_gas_proto_init() {
	if File_contract_free_gas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_free_gas_proto_rawDesc), len(file_contract_free_gas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_free_gas_proto_goTypes,
		DependencyIndexes: file_contract_free_gas_proto_depIdxs,
		MessageInfos:      file_contract_free_gas_proto_msgTypes,
	}.Build()
	File_contract_free_gas_proto = out.File
	file_contract_free_gas_proto_goTypes = nil
	file_contract_free_gas_proto_depIdxs = nil
}
