// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: executor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionExe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        []byte                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	WorkerId      uint32                 `protobuf:"varint,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionExe) Reset() {
	*x = TransactionExe{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionExe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionExe) ProtoMessage() {}

func (x *TransactionExe) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionExe.ProtoReflect.Descriptor instead.
func (*TransactionExe) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionExe) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *TransactionExe) GetWorkerId() uint32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type CommittedBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`   // Ta có thể dùng trường 'round' của Certificate
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"` // Tương tự, có thể dùng 'round'
	Transactions  []*TransactionExe      `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommittedBlock) Reset() {
	*x = CommittedBlock{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommittedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommittedBlock) ProtoMessage() {}

func (x *CommittedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommittedBlock.ProtoReflect.Descriptor instead.
func (*CommittedBlock) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *CommittedBlock) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *CommittedBlock) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CommittedBlock) GetTransactions() []*TransactionExe {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CommittedEpochData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*CommittedBlock      `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommittedEpochData) Reset() {
	*x = CommittedEpochData{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommittedEpochData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommittedEpochData) ProtoMessage() {}

func (x *CommittedEpochData) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommittedEpochData.ProtoReflect.Descriptor instead.
func (*CommittedEpochData) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

func (x *CommittedEpochData) GetBlocks() []*CommittedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\x05proto\"E\n" +
	"\x0eTransactionExe\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\rR\bworkerId\"y\n" +
	"\x0eCommittedBlock\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x129\n" +
	"\ftransactions\x18\x03 \x03(\v2\x15.proto.TransactionExeR\ftransactions\"C\n" +
	"\x12CommittedEpochData\x12-\n" +
	"\x06blocks\x18\x01 \x03(\v2\x15.proto.CommittedBlockR\x06blocksB\bZ\x06/protob\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_executor_proto_goTypes = []any{
	(*TransactionExe)(nil),     // 0: proto.TransactionExe
	(*CommittedBlock)(nil),     // 1: proto.CommittedBlock
	(*CommittedEpochData)(nil), // 2: proto.CommittedEpochData
}
var file_executor_proto_depIdxs = []int32{
	0, // 0: proto.CommittedBlock.transactions:type_name -> proto.TransactionExe
	1, // 1: proto.CommittedEpochData.blocks:type_name -> proto.CommittedBlock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
