// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/rpc_request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcRequest đại diện cho một JSON-RPC request gửi qua TCP
type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jsonrpc       string                 `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"` // "2.0"
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`   // e.g. "net_version", "eth_call", "eth_sendRawTransaction"
	Params        [][]byte               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`   // Params dạng bytes (mỗi param được JSON encode)
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`           // Request ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_pkg_proto_rpc_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_request_proto_rawDescGZIP(), []int{0}
}

func (x *RpcRequest) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *RpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcRequest) GetParams() [][]byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RpcRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RpcResponse đại diện cho một JSON-RPC response trả về qua TCP
type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jsonrpc       string                 `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"` // "2.0"
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`   // Result dạng bytes (JSON encoded)
	Error         *RpcError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // Error nếu có
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`           // Request ID tương ứng
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_pkg_proto_rpc_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_request_proto_rawDescGZIP(), []int{1}
}

func (x *RpcResponse) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *RpcResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RpcResponse) GetError() *RpcError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RpcResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RpcError đại diện cho lỗi trong JSON-RPC
type RpcError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcError) Reset() {
	*x = RpcError{}
	mi := &file_pkg_proto_rpc_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcError) ProtoMessage() {}

func (x *RpcError) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rpc_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcError.ProtoReflect.Descriptor instead.
func (*RpcError) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rpc_request_proto_rawDescGZIP(), []int{2}
}

func (x *RpcError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RpcError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RpcError) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_pkg_proto_rpc_request_proto protoreflect.FileDescriptor

const file_pkg_proto_rpc_request_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/rpc_request.proto\x12\vrpc_request\"f\n" +
	"\n" +
	"RpcRequest\x12\x18\n" +
	"\ajsonrpc\x18\x01 \x01(\tR\ajsonrpc\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06params\x18\x03 \x03(\fR\x06params\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"|\n" +
	"\vRpcResponse\x12\x18\n" +
	"\ajsonrpc\x18\x01 \x01(\tR\ajsonrpc\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.rpc_request.RpcErrorR\x05error\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"L\n" +
	"\bRpcError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04dataB5Z3github.com/meta-node-blockchain/meta-node/pkg/protob\x06proto3"

var (
	file_pkg_proto_rpc_request_proto_rawDescOnce sync.Once
	file_pkg_proto_rpc_request_proto_rawDescData []byte
)

func file_pkg_proto_rpc_request_proto_rawDescGZIP() []byte {
	file_pkg_proto_rpc_request_proto_rawDescOnce.Do(func() {
		file_pkg_proto_rpc_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_rpc_request_proto_rawDesc), len(file_pkg_proto_rpc_request_proto_rawDesc)))
	})
	return file_pkg_proto_rpc_request_proto_rawDescData
}

var file_pkg_proto_rpc_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_rpc_request_proto_goTypes = []any{
	(*RpcRequest)(nil),  // 0: rpc_request.RpcRequest
	(*RpcResponse)(nil), // 1: rpc_request.RpcResponse
	(*RpcError)(nil),    // 2: rpc_request.RpcError
}
var file_pkg_proto_rpc_request_proto_depIdxs = []int32{
	2, // 0: rpc_request.RpcResponse.error:type_name -> rpc_request.RpcError
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_rpc_request_proto_init() }
func file_pkg_proto_rpc_request_proto_init() {
	if File_pkg_proto_rpc_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_rpc_request_proto_rawDesc), len(file_pkg_proto_rpc_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_rpc_request_proto_goTypes,
		DependencyIndexes: file_pkg_proto_rpc_request_proto_depIdxs,
		MessageInfos:      file_pkg_proto_rpc_request_proto_msgTypes,
	}.Build()
	File_pkg_proto_rpc_request_proto = out.File
	file_pkg_proto_rpc_request_proto_goTypes = nil
	file_pkg_proto_rpc_request_proto_depIdxs = nil
}
