// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_receipt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcLogEntry - Log entry dùng chung cho cả Event và Receipt
// Tất cả fields dùng string để khớp với chain JSON output (hex format)
type RpcLogEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Address          string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`                                           // Contract address
	Topics           []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`                                             // Topics (event signature + indexed params)
	Data             string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                 // Non-indexed event data (hex)
	BlockNumber      string                 `protobuf:"bytes,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`                // Block number (hex)
	TransactionHash  string                 `protobuf:"bytes,5,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`    // Transaction hash
	BlockHash        string                 `protobuf:"bytes,6,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`                      // Block hash
	TransactionIndex string                 `protobuf:"bytes,7,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"` // Transaction index (hex)
	LogIndex         string                 `protobuf:"bytes,8,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`                         // Log index (hex)
	Removed          bool                   `protobuf:"varint,9,opt,name=removed,proto3" json:"removed,omitempty"`                                          // Removed flag (reorg)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RpcLogEntry) Reset() {
	*x = RpcLogEntry{}
	mi := &file_rpc_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcLogEntry) ProtoMessage() {}

func (x *RpcLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcLogEntry.ProtoReflect.Descriptor instead.
func (*RpcLogEntry) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *RpcLogEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RpcLogEntry) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *RpcLogEntry) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RpcLogEntry) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *RpcLogEntry) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *RpcLogEntry) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *RpcLogEntry) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *RpcLogEntry) GetLogIndex() string {
	if x != nil {
		return x.LogIndex
	}
	return ""
}

func (x *RpcLogEntry) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// RpcEvent - Subscription event notification = subscription_id + log entry
type RpcEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"` // Subscription ID (0xabc...)
	Log            *RpcLogEntry           `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`                                             // Log entry data
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RpcEvent) Reset() {
	*x = RpcEvent{}
	mi := &file_rpc_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcEvent) ProtoMessage() {}

func (x *RpcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcEvent.ProtoReflect.Descriptor instead.
func (*RpcEvent) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *RpcEvent) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *RpcEvent) GetLog() *RpcLogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

// RpcReceipt - Transaction receipt gửi qua TCP (pure protobuf)
type RpcReceipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash   string                 `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	From              string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	ContractAddress   string                 `protobuf:"bytes,4,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Nếu deploy contract
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                          // "0x1" = success, "0x0" = fail
	GasUsed           string                 `protobuf:"bytes,6,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`                         // Hex string
	CumulativeGasUsed string                 `protobuf:"bytes,7,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	EffectiveGasPrice string                 `protobuf:"bytes,8,opt,name=effective_gas_price,json=effectiveGasPrice,proto3" json:"effective_gas_price,omitempty"`
	BlockHash         string                 `protobuf:"bytes,9,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber       string                 `protobuf:"bytes,10,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"` // Hex string
	TransactionIndex  string                 `protobuf:"bytes,11,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	Type              string                 `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"` // Transaction type
	Logs              []*RpcLogEntry         `protobuf:"bytes,13,rep,name=logs,proto3" json:"logs,omitempty"` // Dùng chung RpcLogEntry
	LogsBloom         string                 `protobuf:"bytes,14,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RpcReceipt) Reset() {
	*x = RpcReceipt{}
	mi := &file_rpc_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcReceipt) ProtoMessage() {}

func (x *RpcReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcReceipt.ProtoReflect.Descriptor instead.
func (*RpcReceipt) Descriptor() ([]byte, []int) {
	return file_rpc_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *RpcReceipt) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *RpcReceipt) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RpcReceipt) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *RpcReceipt) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *RpcReceipt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RpcReceipt) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

func (x *RpcReceipt) GetCumulativeGasUsed() string {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return ""
}

func (x *RpcReceipt) GetEffectiveGasPrice() string {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return ""
}

func (x *RpcReceipt) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *RpcReceipt) GetBlockNumber() string {
	if x != nil {
		return x.BlockNumber
	}
	return ""
}

func (x *RpcReceipt) GetTransactionIndex() string {
	if x != nil {
		return x.TransactionIndex
	}
	return ""
}

func (x *RpcReceipt) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RpcReceipt) GetLogs() []*RpcLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *RpcReceipt) GetLogsBloom() string {
	if x != nil {
		return x.LogsBloom
	}
	return ""
}

var File_rpc_receipt_proto protoreflect.FileDescriptor

const file_rpc_receipt_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_receipt.proto\x12\vrpc_request\"\xa4\x02\n" +
	"\vRpcLogEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12!\n" +
	"\fblock_number\x18\x04 \x01(\tR\vblockNumber\x12)\n" +
	"\x10transaction_hash\x18\x05 \x01(\tR\x0ftransactionHash\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x06 \x01(\tR\tblockHash\x12+\n" +
	"\x11transaction_index\x18\a \x01(\tR\x10transactionIndex\x12\x1b\n" +
	"\tlog_index\x18\b \x01(\tR\blogIndex\x12\x18\n" +
	"\aremoved\x18\t \x01(\bR\aremoved\"_\n" +
	"\bRpcEvent\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12*\n" +
	"\x03log\x18\x02 \x01(\v2\x18.rpc_request.RpcLogEntryR\x03log\"\xe9\x03\n" +
	"\n" +
	"RpcReceipt\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12)\n" +
	"\x10contract_address\x18\x04 \x01(\tR\x0fcontractAddress\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x19\n" +
	"\bgas_used\x18\x06 \x01(\tR\agasUsed\x12.\n" +
	"\x13cumulative_gas_used\x18\a \x01(\tR\x11cumulativeGasUsed\x12.\n" +
	"\x13effective_gas_price\x18\b \x01(\tR\x11effectiveGasPrice\x12\x1d\n" +
	"\n" +
	"block_hash\x18\t \x01(\tR\tblockHash\x12!\n" +
	"\fblock_number\x18\n" +
	" \x01(\tR\vblockNumber\x12+\n" +
	"\x11transaction_index\x18\v \x01(\tR\x10transactionIndex\x12\x12\n" +
	"\x04type\x18\f \x01(\tR\x04type\x12,\n" +
	"\x04logs\x18\r \x03(\v2\x18.rpc_request.RpcLogEntryR\x04logs\x12\x1d\n" +
	"\n" +
	"logs_bloom\x18\x0e \x01(\tR\tlogsBloomB5Z3github.com/meta-node-blockchain/meta-node/pkg/protob\x06proto3"

var (
	file_rpc_receipt_proto_rawDescOnce sync.Once
	file_rpc_receipt_proto_rawDescData []byte
)

func file_rpc_receipt_proto_rawDescGZIP() []byte {
	file_rpc_receipt_proto_rawDescOnce.Do(func() {
		file_rpc_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_receipt_proto_rawDesc), len(file_rpc_receipt_proto_rawDesc)))
	})
	return file_rpc_receipt_proto_rawDescData
}

var file_rpc_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_receipt_proto_goTypes = []any{
	(*RpcLogEntry)(nil), // 0: rpc_request.RpcLogEntry
	(*RpcEvent)(nil),    // 1: rpc_request.RpcEvent
	(*RpcReceipt)(nil),  // 2: rpc_request.RpcReceipt
}
var file_rpc_receipt_proto_depIdxs = []int32{
	0, // 0: rpc_request.RpcEvent.log:type_name -> rpc_request.RpcLogEntry
	0, // 1: rpc_request.RpcReceipt.logs:type_name -> rpc_request.RpcLogEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_receipt_proto_init() }
func file_rpc_receipt_proto_init() {
	if File_rpc_receipt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_receipt_proto_rawDesc), len(file_rpc_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_receipt_proto_goTypes,
		DependencyIndexes: file_rpc_receipt_proto_depIdxs,
		MessageInfos:      file_rpc_receipt_proto_msgTypes,
	}.Build()
	File_rpc_receipt_proto = out.File
	file_rpc_receipt_proto_goTypes = nil
	file_rpc_receipt_proto_depIdxs = nil
}
